# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Luke Anglin
tagline:          Computer Science and Engineering Student
description:      Software Engineering, DevOps, Data Science
domain: luke-anglin.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://luke-anglin.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /luke-anglin/      # place folder name if the site is served in a subfolder

author:
  name:           Luke Anglin
 # url:            https://twitter.com/mdo

plugins: 
 - jekyll-paginate

paginate:         5
paginate_path: 'page:num'

# Custom vars
# Collections 
version:          2.1.0

github:
  repo:           https://github.com/luke-anglin/lukes_site

defaults:
  - scope:
      path: 'static/assets/media'
    values:
      image: true
