# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty

# Setup
title:            Luke Anglin
tagline:          Computer Science and Engineering Student
description:      Software Engineering, DevOps, Data Science
url:              http://localhost:4000/
baseurl:          /

author:
  name:           Luke Anglin
 # url:            https://twitter.com/mdo

plugins: 
 - 'jekyll-paginate'

paginate:         5
paginate_path: 'page:num'

# Custom vars
# Collections 
collections: 
  - ml
collections_dir: _collections
version:          2.1.0

github:
  repo:           https://github.com/luke-anglin/lukes_site

defaults:
  - scope:
      path: 'static/assets/media'
    values:
      image: true
